name: BlazinHud
author: iiFlamiinBlaze
version: 1.0.4
description: An advanced custom hud plugin
main: iiFlamiinBlaze\BlazinHud\BlazinHud
api: 3.0.0
commands:
 blazinhud:
  description: BlazinHud config management command
  permission: blazinhud.command
permissions:
 blazinhud.command:
  default: op
