name: BlazinHud
author: iiFlamiinBlaze
version: 1.0.1
description: An advanced custom hud plugin
main: iiFlamiinBlaze\BlazinHud\BlazinHud
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
commands:
 blazinhud:
  description: BlazinHud config management command
  permission: blazinjoin.command
permissions:
 blazinjoin.command:
  default: op